-- Seed das 150 perguntas das 4 caixinhas da Tecelaria
-- Execute este script no TiDB para popular a tabela question_boxes

-- Limpar perguntas existentes (se houver)
DELETE FROM question_boxes;

-- CAIXINHA 1: "Comece Por Aqui" (Obrigatórias/Cadastrais) - 15 perguntas
INSERT INTO question_boxes (box, boxName, number, question) VALUES
(1, 'Comece Por Aqui', 1, 'Qual é o seu nome completo?'),
(1, 'Comece Por Aqui', 2, 'Qual é a sua data de nascimento?'),
(1, 'Comece Por Aqui', 3, 'Onde você nasceu? (cidade e estado)'),
(1, 'Comece Por Aqui', 4, 'Qual é o nome completo dos seus pais?'),
(1, 'Comece Por Aqui', 5, 'Você tem irmãos? Quais são os nomes deles?'),
(1, 'Comece Por Aqui', 6, 'Qual foi a sua profissão principal?'),
(1, 'Comece Por Aqui', 7, 'Você é casado(a)? Qual o nome do seu cônjuge?'),
(1, 'Comece Por Aqui', 8, 'Você tem filhos? Quais são os nomes deles?'),
(1, 'Comece Por Aqui', 9, 'Você tem netos? Quantos?'),
(1, 'Comece Por Aqui', 10, 'Em que cidade você mora atualmente?'),
(1, 'Comece Por Aqui', 11, 'Qual é a sua religião ou crença espiritual?'),
(1, 'Comece Por Aqui', 12, 'Há quanto tempo você mora na sua cidade atual?'),
(1, 'Comece Por Aqui', 13, 'Qual é o seu estado civil?'),
(1, 'Comece Por Aqui', 14, 'Você tem algum apelido? Como surgiu?'),
(1, 'Comece Por Aqui', 15, 'Há alguma história especial por trás do seu nome?');

-- CAIXINHA 2: "Siga Por Aqui" (Desejáveis) - 45 perguntas
INSERT INTO question_boxes (box, boxName, number, question) VALUES
(2, 'Siga Por Aqui', 1, 'Qual é o seu time de futebol?'),
(2, 'Siga Por Aqui', 2, 'Qual é o seu esporte favorito?'),
(2, 'Siga Por Aqui', 3, 'Você tem alguma memória marcante de Copa do Mundo?'),
(2, 'Siga Por Aqui', 4, 'Você tem alguma memória de Olimpíadas?'),
(2, 'Siga Por Aqui', 5, 'Qual era o seu grande sonho quando era jovem?'),
(2, 'Siga Por Aqui', 6, 'Qual é o seu programa de TV favorito?'),
(2, 'Siga Por Aqui', 7, 'Qual é o seu livro favorito?'),
(2, 'Siga Por Aqui', 8, 'Qual filme te marcou profundamente?'),
(2, 'Siga Por Aqui', 9, 'Qual é a sua música ou cantor(a) favorito(a)?'),
(2, 'Siga Por Aqui', 10, 'Você tem algum hobby ou passatempo favorito?'),
(2, 'Siga Por Aqui', 11, 'Qual é a sua comida favorita?'),
(2, 'Siga Por Aqui', 12, 'Você tem algum doce com sabor de infância?'),
(2, 'Siga Por Aqui', 13, 'Qual é o seu sabor de sorvete preferido?'),
(2, 'Siga Por Aqui', 14, 'Você tem receitas especiais para compartilhar?'),
(2, 'Siga Por Aqui', 15, 'Qual é a sua cor favorita?'),
(2, 'Siga Por Aqui', 16, 'Você tem alguma tradição familiar especial?'),
(2, 'Siga Por Aqui', 17, 'Qual é o seu feriado ou data comemorativa favorita?'),
(2, 'Siga Por Aqui', 18, 'Você é mais do dia ou mais da noite?'),
(2, 'Siga Por Aqui', 19, 'Qual é o seu animal favorito?'),
(2, 'Siga Por Aqui', 20, 'Você tem ou teve algum animal de estimação?'),
(2, 'Siga Por Aqui', 21, 'Qual é o seu lugar favorito no mundo?'),
(2, 'Siga Por Aqui', 22, 'Você prefere praia ou montanha?'),
(2, 'Siga Por Aqui', 23, 'Qual é a sua estação do ano favorita?'),
(2, 'Siga Por Aqui', 24, 'Você tem algum talento ou habilidade especial?'),
(2, 'Siga Por Aqui', 25, 'Qual é o seu maior orgulho na vida?'),
(2, 'Siga Por Aqui', 26, 'Você praticou algum esporte quando jovem?'),
(2, 'Siga Por Aqui', 27, 'Você toca algum instrumento musical?'),
(2, 'Siga Por Aqui', 28, 'Qual é o seu tipo de música favorito?'),
(2, 'Siga Por Aqui', 29, 'Você gosta de dançar? Qual é o seu estilo?'),
(2, 'Siga Por Aqui', 30, 'Qual é o seu prato típico favorito da sua região?'),
(2, 'Siga Por Aqui', 31, 'Você tem alguma superstição ou crendice?'),
(2, 'Siga Por Aqui', 32, 'Qual é o seu cheiro favorito?'),
(2, 'Siga Por Aqui', 33, 'Você tem alguma coleção?'),
(2, 'Siga Por Aqui', 34, 'Qual é o seu tipo de roupa favorita?'),
(2, 'Siga Por Aqui', 35, 'Você tem algum acessório ou joia especial?'),
(2, 'Siga Por Aqui', 36, 'Qual é o seu perfume ou fragrância favorita?'),
(2, 'Siga Por Aqui', 37, 'Você gosta de cozinhar? Qual é o seu prato especial?'),
(2, 'Siga Por Aqui', 38, 'Você gosta de jardinagem? Tem plantas favoritas?'),
(2, 'Siga Por Aqui', 39, 'Qual é o seu tipo de clima favorito?'),
(2, 'Siga Por Aqui', 40, 'Você prefere cidade ou campo?'),
(2, 'Siga Por Aqui', 41, 'Qual é o seu meio de transporte favorito?'),
(2, 'Siga Por Aqui', 42, 'Você gosta de ler? Qual gênero literário prefere?'),
(2, 'Siga Por Aqui', 43, 'Você assiste novelas? Tem alguma favorita?'),
(2, 'Siga Por Aqui', 44, 'Qual é o seu tipo de filme favorito?'),
(2, 'Siga Por Aqui', 45, 'Você tem algum artista ou ator favorito?');

-- CAIXINHA 3: "Lembranças Profundas" (Amplas/Reflexivas) - 45 perguntas
INSERT INTO question_boxes (box, boxName, number, question) VALUES
(3, 'Lembranças Profundas', 1, 'Qual memória te faz sentir mais agradecido e feliz?'),
(3, 'Lembranças Profundas', 2, 'Se você tivesse algum arrependimento na vida, qual seria?'),
(3, 'Lembranças Profundas', 3, 'O que você diria para o seu eu de 18 anos?'),
(3, 'Lembranças Profundas', 4, 'Qual foi o momento mais feliz da sua vida?'),
(3, 'Lembranças Profundas', 5, 'Qual foi o momento mais difícil que você superou?'),
(3, 'Lembranças Profundas', 6, 'Qual foi a melhor decisão que você já tomou?'),
(3, 'Lembranças Profundas', 7, 'Qual foi a pior decisão que você já tomou?'),
(3, 'Lembranças Profundas', 8, 'Quem foi a pessoa mais importante da sua vida?'),
(3, 'Lembranças Profundas', 9, 'Qual foi o maior desafio que você enfrentou?'),
(3, 'Lembranças Profundas', 10, 'Qual foi a maior conquista da sua vida?'),
(3, 'Lembranças Profundas', 11, 'O que você mais valoriza na vida?'),
(3, 'Lembranças Profundas', 12, 'Qual conselho você daria para as próximas gerações?'),
(3, 'Lembranças Profundas', 13, 'O que você aprendeu com os erros que cometeu?'),
(3, 'Lembranças Profundas', 14, 'Qual foi o maior amor da sua vida?'),
(3, 'Lembranças Profundas', 15, 'O que te faz sentir realizado(a)?'),
(3, 'Lembranças Profundas', 16, 'Qual foi o momento em que você se sentiu mais orgulhoso(a)?'),
(3, 'Lembranças Profundas', 17, 'O que você gostaria de ter feito diferente na vida?'),
(3, 'Lembranças Profundas', 18, 'Qual foi a maior lição que a vida te ensinou?'),
(3, 'Lembranças Profundas', 19, 'O que você espera que as pessoas lembrem de você?'),
(3, 'Lembranças Profundas', 20, 'Qual foi o momento em que você se sentiu mais amado(a)?'),
(3, 'Lembranças Profundas', 21, 'O que te faz sentir em paz?'),
(3, 'Lembranças Profundas', 22, 'Qual foi a maior mudança que você viveu?'),
(3, 'Lembranças Profundas', 23, 'O que você faria se pudesse voltar no tempo?'),
(3, 'Lembranças Profundas', 24, 'Qual foi o momento mais emocionante da sua vida?'),
(3, 'Lembranças Profundas', 25, 'O que você mais admira nas pessoas?'),
(3, 'Lembranças Profundas', 26, 'Qual foi o maior sacrifício que você fez?'),
(3, 'Lembranças Profundas', 27, 'O que te motiva a continuar?'),
(3, 'Lembranças Profundas', 28, 'Qual foi a maior surpresa da sua vida?'),
(3, 'Lembranças Profundas', 29, 'O que você gostaria de ter aprendido mais cedo?'),
(3, 'Lembranças Profundas', 30, 'Qual foi o momento em que você se sentiu mais corajoso(a)?'),
(3, 'Lembranças Profundas', 31, 'O que você considera sucesso na vida?'),
(3, 'Lembranças Profundas', 32, 'Qual foi a maior transformação que você viveu?'),
(3, 'Lembranças Profundas', 33, 'O que te faz sentir vivo(a)?'),
(3, 'Lembranças Profundas', 34, 'Qual foi o momento em que você se sentiu mais vulnerável?'),
(3, 'Lembranças Profundas', 35, 'O que você mais teme na vida?'),
(3, 'Lembranças Profundas', 36, 'Qual foi a maior alegria que você sentiu?'),
(3, 'Lembranças Profundas', 37, 'O que você faria se não tivesse medo?'),
(3, 'Lembranças Profundas', 38, 'Qual foi o momento em que você se sentiu mais livre?'),
(3, 'Lembranças Profundas', 39, 'O que você mais admira em si mesmo(a)?'),
(3, 'Lembranças Profundas', 40, 'Qual foi a maior dor que você superou?'),
(3, 'Lembranças Profundas', 41, 'O que te faz sentir completo(a)?'),
(3, 'Lembranças Profundas', 42, 'Qual foi o momento em que você se sentiu mais forte?'),
(3, 'Lembranças Profundas', 43, 'O que você gostaria de deixar como legado?'),
(3, 'Lembranças Profundas', 44, 'Qual foi a maior gratidão que você sentiu?'),
(3, 'Lembranças Profundas', 45, 'O que você diria para o seu eu do futuro?');

-- CAIXINHA 4: "Detalhes que Contam" (Específicas) - 45 perguntas
INSERT INTO question_boxes (box, boxName, number, question) VALUES
(4, 'Detalhes que Contam', 1, 'Qual era o nome da sua primeira escola?'),
(4, 'Detalhes que Contam', 2, 'Qual era o nome do(a) seu(sua) primeiro(a) professor(a)?'),
(4, 'Detalhes que Contam', 3, 'Qual era o nome do seu primeiro amor?'),
(4, 'Detalhes que Contam', 4, 'Qual era o endereço da casa onde você cresceu?'),
(4, 'Detalhes que Contam', 5, 'Qual era o nome do seu melhor amigo de infância?'),
(4, 'Detalhes que Contam', 6, 'Qual era o seu brinquedo favorito?'),
(4, 'Detalhes que Contam', 7, 'Qual era a sua brincadeira favorita?'),
(4, 'Detalhes que Contam', 8, 'Qual era o nome do seu primeiro emprego?'),
(4, 'Detalhes que Contam', 9, 'Qual era o seu salário no primeiro emprego?'),
(4, 'Detalhes que Contam', 10, 'Qual era o nome do seu primeiro carro?'),
(4, 'Detalhes que Contam', 11, 'Qual era o nome da rua onde você morava?'),
(4, 'Detalhes que Contam', 12, 'Qual era o nome do seu avô paterno?'),
(4, 'Detalhes que Contam', 13, 'Qual era o nome da sua avó paterna?'),
(4, 'Detalhes que Contam', 14, 'Qual era o nome do seu avô materno?'),
(4, 'Detalhes que Contam', 15, 'Qual era o nome da sua avó materna?'),
(4, 'Detalhes que Contam', 16, 'Qual era a profissão do seu pai?'),
(4, 'Detalhes que Contam', 17, 'Qual era a profissão da sua mãe?'),
(4, 'Detalhes que Contam', 18, 'Qual era o nome da igreja/templo que você frequentava?'),
(4, 'Detalhes que Contam', 19, 'Qual era o nome do seu médico de infância?'),
(4, 'Detalhes que Contam', 20, 'Qual era o nome do mercado/armazém do seu bairro?'),
(4, 'Detalhes que Contam', 21, 'Qual era o nome do seu dentista?'),
(4, 'Detalhes que Contam', 22, 'Qual era o número da sua casa de infância?'),
(4, 'Detalhes que Contam', 23, 'Qual era o nome do seu bairro?'),
(4, 'Detalhes que Contam', 24, 'Qual era o nome da padaria que você frequentava?'),
(4, 'Detalhes que Contam', 25, 'Qual era o preço do pão quando você era criança?'),
(4, 'Detalhes que Contam', 26, 'Qual era o nome do seu time de futebol de infância?'),
(4, 'Detalhes que Contam', 27, 'Qual era o nome do cinema que você frequentava?'),
(4, 'Detalhes que Contam', 28, 'Qual era o nome do parque ou praça que você brincava?'),
(4, 'Detalhes que Contam', 29, 'Qual era o nome do seu vizinho mais próximo?'),
(4, 'Detalhes que Contam', 30, 'Qual era o nome da sua primeira namorada/namorado?'),
(4, 'Detalhes que Contam', 31, 'Qual era o nome do hospital onde você nasceu?'),
(4, 'Detalhes que Contam', 32, 'Qual era o nome da maternidade?'),
(4, 'Detalhes que Contam', 33, 'Qual era o nome do cartório onde você foi registrado?'),
(4, 'Detalhes que Contam', 34, 'Qual era o nome da farmácia do seu bairro?'),
(4, 'Detalhes que Contam', 35, 'Qual era o nome do açougue que sua família frequentava?'),
(4, 'Detalhes que Contam', 36, 'Qual era o nome da feira ou mercado municipal?'),
(4, 'Detalhes que Contam', 37, 'Qual era o nome do seu professor favorito?'),
(4, 'Detalhes que Contam', 38, 'Qual era o nome da sua matéria favorita na escola?'),
(4, 'Detalhes que Contam', 39, 'Qual era o nome do diretor da sua escola?'),
(4, 'Detalhes que Contam', 40, 'Qual era o nome do seu colega de classe mais próximo?'),
(4, 'Detalhes que Contam', 41, 'Qual era o nome do ônibus ou linha que você pegava?'),
(4, 'Detalhes que Contam', 42, 'Qual era o nome da rádio que você ouvia?'),
(4, 'Detalhes que Contam', 43, 'Qual era o nome do programa de rádio favorito?'),
(4, 'Detalhes que Contam', 44, 'Qual era o nome da novela que marcou sua juventude?'),
(4, 'Detalhes que Contam', 45, 'Qual era o nome do apresentador de TV favorito?');
